components {
  id: "Etoile"
  component: "/Normal/Scripts/Etoile.script"
}
embedded_components {
  id: "sprite"
  type: "sprite"
  data: "default_animation: \"E_rouge\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Normal/Atlas/Espace.atlas\"\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"Etoile\"\n"
  "mask: \"Curseur\"\n"
  "mask: \"Etoile\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 16.0\n"
  "}\n"
  ""
}
embedded_components {
  id: "sprite_close"
  type: "sprite"
  data: "default_animation: \"etoile_rouge\"\n"
  "material: \"/builtins/materials/sprite.material\"\n"
  "textures {\n"
  "  sampler: \"texture_sampler\"\n"
  "  texture: \"/Normal/Atlas/Systeme.atlas\"\n"
  "}\n"
  ""
}
