components {
  id: "CollisionObject"
  component: "/main/UI/CollisionObject.script"
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_TRIGGER\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"Gui\"\n"
  "mask: \"Curseur\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "    id: \"Collision\"\n"
  "  }\n"
  "  data: 160.0\n"
  "  data: 540.0\n"
  "  data: 50.0\n"
  "}\n"
  ""
}
